finter/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'main.views.index', name='index'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'infos/', include('infos.urls', namespace='infos')),
    url(r'', include('main.urls', namespace='main')),
    url(r'filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', 'django.contrib.auth.login', name='login')
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infos/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('infos.views',
    url(r'^files/$', 'files', name='files'),
    url(r'^phones/$', 'phones', name='phones'),
    url(r'^subsidairy/(?P<pk>\d+)/$', 'subsidairy', name='subsidairy'),
)

main/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),

    url(r'^ads/$', 'ads_list', name='ads_list'),
    url(r'^create_ad/$', 'create_ad', name='create_ad'),
    url(r'^ads/(?P<pk>\d+)/$', 'ads', name='ads'),
    url(r'^birth/(?P<pk>\d+)/$', 'birth', name='birth'),
    url(r'^books/$', 'books', name='books'),
    url(r'^book/(?P<pk>\d+)/$', 'book', name='book'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^calendar/(?P<pk>\d+)/$', 'calendar_event', name='calendar_event'),
    url(r'^company_structure/$', 'company_structure', name='company_structure'),
    url(r'^company_life/$', 'company_life', name='company_life'),
    url(r'^contests/$', 'contests_list', name='contests_list'),
    url(r'^contests/(?P<pk>\d+)/$', 'contests', name='contests'),
    url(r'^directions/$', 'directions', name='directions'),
    url(r'^direction/(?P<pk>\d+)/$', 'direction', name='direction'),
    url(r'^empltraining/$', 'empltraining_list', name='empltraining_list'),
    url(r'^empltraining/(?P<pk>\d+)/$', 'empltraining', name='empltraining'),
    url(r'^questions/$', 'questions', name='questions'),
    url(r'^question/(?P<pk>\d+)/$', 'question', name='question'),
    url(r'^create_question/$', 'create_question', name='create_question'),
    url(r'^quiz/$', 'quiz_list', name='quiz_list'),
    url(r'^quiz/(?P<pk>\d+)/$', 'quiz', name='quiz'),
    url(r'^info/$', 'info', name='info'),
    url(r'^newbies/$', 'newbies', name='newbies'),
    url(r'^newbie/(?P<pk>\d+)/$', 'newbie', name='newbie'),
    url(r'^news/$', 'news_list', name='news_list'),
    url(r'^news/(?P<pk>\d+)/$', 'news', name='news'),
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^plans/$', 'plans', name='plans'),
)

infos/models.py
#coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse

from main.models import DefaultModel, TitlePage

from .choices import FILETYPES


class Subsidairy(TitlePage):
    u''' Дочерняя компания '''
    __unicode__ = lambda self: self.title
    class Meta:
        verbose_name=u'Дочерняя компания'
        verbose_name_plural = u'Дочернии компании'

    def get_absolute_url(self):
        return reverse('infos:subsidairy', kwargs=dict(pk=self.pk))


class DocTemplate(DefaultModel):
    title = models.CharField(max_length=255)
    template = models.FileField(upload_to='docs/')
    file_type = models.CharField(max_length=32, choices=FILETYPES)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name=u'шаблон документа'
        verbose_name_plural = u'шаблоны документов'


class PhoneBook(DefaultModel):
    title = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    subsidairy = models.ForeignKey(Subsidairy, blank=True, null=True,
                                verbose_name=Subsidairy._meta.verbose_name)
    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name=u'Телефонный справочник'
        verbose_name_plural = verbose_name

infos/views.py
#coding: utf-8
from django.db.models import Q

from main.views import ListPage, DetailPage

from .models import DocTemplate, Subsidairy


class FileList(ListPage):
    model=DocTemplate
    template_name='docs.html'

    def get_queryset(self):
        qs = super(FileList, self).get_queryset()
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('title'):
                fld = body.get('title')
                q&= Q(title__icontains=fld)
        return qs.filter(q)
files = FileList.as_view()


subsidairy = DetailPage.as_view(model=Subsidairy,
                        template_name='subsidairy.html')


class PhoneList(ListPage):
    model=Subsidairy
    queryset=Subsidairy.objects.filter(phonebook__isnull=False)
    template_name='phonebook.html'

    def get_queryset(self):
        qs = super(PhoneList, self).get_queryset()
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('fio'):
                fld = body.get('fio')
                q&= Q(title__icontains=fld)
        return qs.filter(q)
phones = PhoneList.as_view()

infos/templates/docs.html
{% extends 'basecontent.html' %}

{% block middle %}
<div class="middlecontentblock">
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    <div class="mainblock">
        <h2>{{title}}</h2>
        <div class="textblock greentopblock">
            <form action="" id="fastSearch" method="GET">
                <input type="text" name="title" id="namesearch" class="fancyfield" placeholder="Поиск документа по имени">
            </form>
        </div>
        <ul class="documentslist">
        {% for file in object_list %}
            <li class="documentitem {{file.file_type}}">
                <a href="{{file.template.url}}" >{{file.title}}<br/>({{file.get_file_type_display}}, {{file.template.size|filesizeformat}})</a>
            </li>
        {% endfor %}
        </ul>
        {% include 'partial/paginator.html' %}
        <div class="clear"><br/></div>
    </div>
</div>
{% endblock %}

infos/templates/phonebook.html
{% extends 'basecontent.html' %}

{% block middle %}
<div class="middlecontentblock">
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    <div class="mainblock">
        <div class="textblock greentopblock">
            <form action="" method="get" class="textsearch">
                <input type="search" name="fio" value="" placeholder="Поиск по компании" class="fancyfield"/>
                <button type="submit" class="lightbluebtn">Найти</button>
            </form>
        </div>
        <div class="textblock">
            <br/>
            <ul class="phonebooklist">
                {% for phone in object_list %}
                <li>
                    <span class="phonename"><a href="{{phone.get_absolute_url}}">{{phone.title}}</a></span>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% include 'partial/paginator.html' %}
        <div class="clear"><br/></div>
    </div>
</div>
{% endblock %}

infos/templates/subsidairy.html
{% extends 'basecontent.html' %}

{% block middle %}
<div class="middlecontentblock">
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    <div class="mainblock">
        <h2>{{title}}</h2>
        <div class="textblock">
            {% block detail_page %}
            <h2>{{ detail_page.title }}</h2>
            {% endblock %}

            <ul class="phonebooklist">
                {% for phone in detail_page.phonebook_set.all %}
                <li>
                    <span class="phonename">{{phone.title}}</span>
                    <span class="phonenumber">{{phone.phone}}</span>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="clear"><br/></div>
    </div>
</div>
{% endblock %}