finter/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'main.views.index', name='index'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'infos/', include('infos.urls', namespace='infos')),
    url(r'', include('main.urls', namespace='main')),
    url(r'filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', 'django.contrib.auth.login', name='login')
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('gallery.views',
    url(r'^image_gallery_list/$', 'image_gallery_list', name='image_gallery_list'),
    url(r'^image_gallery/(?P<pk>\d+)/$', 'image_gallery', name='image_gallery'),
    url(r'^video_gallery_list/$', 'video_gallery_list', name='video_gallery_list'),
    url(r'^video_gallery/(?P<pk>\d+)/$', 'video_gallery', name='video_gallery'),
    url(r'^docs_gallery_list/$', 'docs_gallery_list', name='docs_gallery_list'),
    url(r'^docs_gallery/(?P<pk>\d+)/$', 'docs_gallery', name='docs_gallery'),
)

main/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),

    url(r'^ads/$', 'ads_list', name='ads_list'),
    url(r'^create_ad/$', 'create_ad', name='create_ad'),
    url(r'^ads/(?P<pk>\d+)/$', 'ads', name='ads'),
    url(r'^birth/(?P<pk>\d+)/$', 'birth', name='birth'),
    url(r'^books/$', 'books', name='books'),
    url(r'^book/(?P<pk>\d+)/$', 'book', name='book'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^calendar/(?P<pk>\d+)/$', 'calendar_event', name='calendar_event'),
    url(r'^company_structure/$', 'company_structure', name='company_structure'),
    url(r'^company_life/$', 'company_life', name='company_life'),
    url(r'^contests/$', 'contests_list', name='contests_list'),
    url(r'^contests/(?P<pk>\d+)/$', 'contests', name='contests'),
    url(r'^directions/$', 'directions', name='directions'),
    url(r'^direction/(?P<pk>\d+)/$', 'direction', name='direction'),
    url(r'^empltraining/$', 'empltraining_list', name='empltraining_list'),
    url(r'^empltraining/(?P<pk>\d+)/$', 'empltraining', name='empltraining'),
    url(r'^questions/$', 'questions', name='questions'),
    url(r'^question/(?P<pk>\d+)/$', 'question', name='question'),
    url(r'^create_question/$', 'create_question', name='create_question'),
    url(r'^quiz/$', 'quiz_list', name='quiz_list'),
    url(r'^quiz/(?P<pk>\d+)/$', 'quiz', name='quiz'),
    url(r'^info/$', 'info', name='info'),
    url(r'^newbies/$', 'newbies', name='newbies'),
    url(r'^newbie/(?P<pk>\d+)/$', 'newbie', name='newbie'),
    url(r'^news/$', 'news_list', name='news_list'),
    url(r'^news/(?P<pk>\d+)/$', 'news', name='news'),
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^plans/$', 'plans', name='plans'),
)

gallery/models.py
#coding: utf-8
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

from filer.fields.image import FilerImageField
from embed_video.fields import EmbedVideoField

from main.models import AbstractPage


class ImageGallery(AbstractPage):
    class Meta:
        verbose_name=u'Галерея изображений'
        verbose_name_plural = u'Галереи изображений'

    def get_absolute_url(self):
        return reverse('gallery:image_gallery', kwargs=dict(pk=self.pk))    


class VideoGallery(AbstractPage):
    class Meta:
        verbose_name=u'Галерея видео'
        verbose_name_plural = u'Галереи видео'

    def get_absolute_url(self):
        return reverse('gallery:video_gallery', kwargs=dict(pk=self.pk))  


class DocsGallery(AbstractPage):
    class Meta:
        verbose_name=u'Галерея документов'
        verbose_name_plural = u'Галереи документов'

    def get_absolute_url(self):
        return reverse('gallery:docs_gallery', kwargs=dict(pk=self.pk))  


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    gallery = models.ForeignKey(ImageGallery, verbose_name=u'Галерея', null=True)
    image = FilerImageField()

    def __unicode__(self):
        name = self.image.name or self.image.original_filename
        if self.gallery:
            return self.gallery.title + u' ' + name

    class Meta:
        verbose_name=u'изображение'
        verbose_name_plural = u'изображения'

    def get_absolute_url(self):
        return reverse('gallery:image', kwargs=dict(pk=self.pk))


class Video(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    gallery = models.ForeignKey(VideoGallery, verbose_name=u'Галерея', null=True)
    video = EmbedVideoField()

    def __unicode__(self):
        name = self.video
        if self.gallery:
            return self.gallery.title + u' ' + name

    class Meta:
        verbose_name=u'видео'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('gallery:video', kwargs=dict(pk=self.pk))


class DocFile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    gallery = models.ForeignKey(DocsGallery, verbose_name=u'Галерея', null=True)
    doc_file = models.FileField(upload_to='docs/')

    def __unicode__(self):
        name = self.doc_file.name
        if self.gallery:
            return self.gallery.title + u' ' + name

    class Meta:
        verbose_name=u'документ'
        verbose_name_plural = u'документы'

    def get_absolute_url(self):
        return reverse('gallery:doc_file', kwargs=dict(pk=self.pk))

gallery/views.py
#coding: utf-8
from main.views import DetailPage, ListPage

from .models import ImageGallery, VideoGallery, DocsGallery


image_gallery_list = ListPage.as_view(model=ImageGallery)
video_gallery_list = ListPage.as_view(model=VideoGallery)
docs_gallery_list = ListPage.as_view(model=DocsGallery)

image_gallery = DetailPage.as_view( model=ImageGallery,
                                    template_name='image_gallery.html')
video_gallery = DetailPage.as_view( model=VideoGallery,
                                    template_name='video_gallery.html')
docs_gallery = DetailPage.as_view(  model=DocsGallery,
                                    template_name='docs_gallery.html')

gallery/templates/docs_gallery.html
{% extends 'basecontent.html' %}

{% block middle %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
        <div class="sideblock bluebanner">
            <section class="sideblocktext centertext">
                <div class="clear"></div>
            </section>
        </div>
        <div class="sideblock">
        </div>
    </div>
    {% endblock %}
    <div class="mainblock">
        <div class="textblock">
        {% block detail_page %}
            <p><time>{{ detail_page.created }}</time></p>
            <p>{{ detail_page.title }}</p>
            {% block content %}
                {{detail_page.content|safe}}
            {% endblock %}
            {% for item in detail_page.docfile_set.all %}
                <a href="{{item.doc_file.url}}">{{item.doc_file.name}}</a><br/>
            {% endfor %}
        {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/image_gallery.html
{% extends 'basecontent.html' %}
{% load thumbnail %}
{% block middle %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
        <div class="sideblock bluebanner">
            <section class="sideblocktext centertext">
                <div class="clear"></div>
            </section>
        </div>
        <div class="sideblock">
        </div>
    </div>
    {% endblock %}
    <div class="mainblock">
        <div class="textblock">
        {% block detail_page %}
            <p><time>{{ detail_page.created }}</time></p>
            <p>{{ detail_page.title }}</p>
            {% block content %}
                {{detail_page.content|safe}}
            {% endblock %}
        {% endblock %}
        </div>
    {% for image in detail_page.image_set.all %}
        <div class="imagegallerybanner">
            <img src="{% thumbnail image.image 250x250 crop %}" alt="image.name">
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

gallery/templates/video_gallery.html
{% extends 'basecontent.html' %}
{% load embed_video_tags %}
{% block middle %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
        <div class="sideblock bluebanner">
            <section class="sideblocktext centertext">
                <div class="clear"></div>
            </section>
        </div>
        <div class="sideblock">
        </div>
    </div>
    {% endblock %}
    <div class="mainblock">
        <div class="textblock">
        {% block detail_page %}
            <p><time>{{ detail_page.created }}</time></p>
            <p>{{ detail_page.title }}</p>
            {% block content %}
                {{detail_page.content|safe}}
            {% endblock %}
        {% endblock %}
        </div>
    {% for item in detail_page.video_set.all %}
        <div class="imagegallerybanner">
            {% video item.video '320 x 240' %}
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}