accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('accounts.views',
    url(r'^new_users/$', 'new_users', name='new_users'),
    url(r'^on_vacation_users/$', 'on_vacation_users', name='on_vacation_users'),
    url(r'^birthday_users/$', 'birthday_users', name='birthday_users'),
    url(r'^profile/(?P<pk>\d+)/$', 'profile', name='profile'),


    url(r'^userdetails/(?P<pk>\d+)/$', 'userdetails', name='userdetails'),
)

filestorage/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('filestorage.views',
    url(r'^gallery_list/$', 'gallery_list', name='gallery_list'),
    url(r'^gallery/(?P<pk>\d+)/$', 'gallery', name='gallery'),
    url(r'^image_gallery_list/$', 'image_gallery_list', name='image_gallery_list'),
    url(r'^image_gallery/(?P<pk>\d+)/$', 'image_gallery', name='image_gallery'),
    url(r'^video_gallery_list/$', 'video_gallery_list', name='video_gallery_list'),
    url(r'^video_gallery/(?P<pk>\d+)/$', 'video_gallery', name='video_gallery'),
    url(r'^docs_gallery_list/$', 'docs_gallery_list', name='docs_gallery_list'),
    url(r'^docs_gallery/(?P<pk>\d+)/$', 'docs_gallery', name='docs_gallery'),
)

finter/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'main.views.index', name='index'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'infos/', include('infos.urls', namespace='infos')),
    url(r'', include('main.urls', namespace='main')),
    url(r'filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', 'django.contrib.auth.login', name='login')
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('gallery.views',
    url(r'^image_gallery_list/$', 'image_gallery_list', name='image_gallery_list'),
    url(r'^image_gallery/(?P<pk>\d+)/$', 'image_gallery', name='image_gallery'),
    url(r'^video_gallery_list/$', 'video_gallery_list', name='video_gallery_list'),
    url(r'^video_gallery/(?P<pk>\d+)/$', 'video_gallery', name='video_gallery'),
    url(r'^docs_gallery_list/$', 'docs_gallery_list', name='docs_gallery_list'),
    url(r'^docs_gallery/(?P<pk>\d+)/$', 'docs_gallery', name='docs_gallery'),
)

infos/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('infos.views',
    url(r'^files/$', 'files', name='files'),
    url(r'^phones/$', 'phones', name='phones'),
    url(r'^subsidairy/(?P<pk>\d+)/$', 'subsidairy', name='subsidairy'),
)

main/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),

    url(r'^ads/$', 'ads_list', name='ads_list'),
    url(r'^create_ad/$', 'create_ad', name='create_ad'),
    url(r'^ads/(?P<pk>\d+)/$', 'ads', name='ads'),
    url(r'^birth/(?P<pk>\d+)/$', 'birth', name='birth'),
    url(r'^books/$', 'books', name='books'),
    url(r'^book/(?P<pk>\d+)/$', 'book', name='book'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^calendar/(?P<pk>\d+)/$', 'calendar_event', name='calendar_event'),
    url(r'^company_structure/$', 'company_structure', name='company_structure'),
    url(r'^company_life/$', 'company_life', name='company_life'),
    url(r'^contests/$', 'contests_list', name='contests_list'),
    url(r'^contests/(?P<pk>\d+)/$', 'contests', name='contests'),
    url(r'^directions/$', 'directions', name='directions'),
    url(r'^direction/(?P<pk>\d+)/$', 'direction', name='direction'),
    url(r'^empltraining/$', 'empltraining_list', name='empltraining_list'),
    url(r'^empltraining/(?P<pk>\d+)/$', 'empltraining', name='empltraining'),
    url(r'^questions/$', 'questions', name='questions'),
    url(r'^question/(?P<pk>\d+)/$', 'question', name='question'),
    url(r'^create_question/$', 'create_question', name='create_question'),
    url(r'^quiz/$', 'quiz_list', name='quiz_list'),
    url(r'^quiz/(?P<pk>\d+)/$', 'quiz', name='quiz'),
    url(r'^info/$', 'info', name='info'),
    url(r'^newbies/$', 'newbies', name='newbies'),
    url(r'^newbie/(?P<pk>\d+)/$', 'newbie', name='newbie'),
    url(r'^news/$', 'news_list', name='news_list'),
    url(r'^news/(?P<pk>\d+)/$', 'news', name='news'),
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^plans/$', 'plans', name='plans'),
)

infos/models.py
#coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse

from main.models import DefaultModel, TitlePage

from .choices import FILETYPES


class Subsidairy(TitlePage):
    u''' Дочерняя компания '''
    __unicode__ = lambda self: self.title
    class Meta:
        verbose_name=u'Дочерняя компания'
        verbose_name_plural = u'Дочернии компании'

    def get_absolute_url(self):
        return reverse('infos:subsidairy', kwargs=dict(pk=self.pk))


class DocTemplate(DefaultModel):
    title = models.CharField(max_length=255)
    template = models.FileField(upload_to='docs/')
    file_type = models.CharField(max_length=32, choices=FILETYPES)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name=u'шаблон документа'
        verbose_name_plural = u'шаблоны документов'


class PhoneBook(DefaultModel):
    title = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    subsidairy = models.ForeignKey(Subsidairy, blank=True, null=True,
                                verbose_name=Subsidairy._meta.verbose_name)
    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name=u'Телефонный справочник'
        verbose_name_plural = verbose_name

main/forms.py
#coding: utf-8
from django import forms

from ckeditor.widgets import CKEditorWidget

from .models import Ad, Wish, Comment


class WishForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Wish
        fields = 'content',


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Comment
        fields = 'content',


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = 'title', 'content'

infos/views.py
#coding: utf-8
from django.db.models import Q

from main.views import ListPage, DetailPage

from .models import DocTemplate, Subsidairy


class FileList(ListPage):
    model=DocTemplate
    template_name='docs.html'

    def get_queryset(self):
        qs = super(FileList, self).get_queryset()
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('title'):
                fld = body.get('title')
                q&= Q(title__icontains=fld)
        return qs.filter(q)
files = FileList.as_view()


subsidairy = DetailPage.as_view(model=Subsidairy,
                        template_name='subsidairy.html')


class PhoneList(ListPage):
    model=Subsidairy
    queryset=Subsidairy.objects.filter(phonebook__isnull=False)
    template_name='phonebook.html'

    def get_queryset(self):
        qs = super(PhoneList, self).get_queryset()
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('fio'):
                fld = body.get('fio')
                q&= Q(title__icontains=fld)
        return qs.filter(q)
phones = PhoneList.as_view()

main/views.py
#coding: utf-8
from django.contrib.auth import get_user_model
User = get_user_model()
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from conversejs.models import XMPPAccount

from filestorage.models import Gallery
from infos.models import DocTemplate, Subsidairy

from .forms import WishForm, CommentForm#, AdForm
from .models import Ad, Book, Calendar, Contest, CompanyStructure
from .models import Direction, BirthDate, Question#, Vacation, 
from .models import News, NewsSliderItem, Quiz, QuizUserVote
from .models import Plan, SystemTunes, Newbie, EmplTraining
from .utils import slice_list

class ContextMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(ContextMixin, self).get_context_data(**kwargs)
        try:
            xmpp_account = XMPPAccount.objects.get(user=self.request.user.pk)
            ctx['user_jid'] = xmpp_account
        except XMPPAccount.DoesNotExist: pass
        ctx['ads'] = slice_list(Ad.objects.all())
        ctx['news'] = slice_list(News.objects.all())
        ctx['calendar_events'] = slice_list(Calendar.objects.all(), 5)
        ctx['clrs'] = ('blue','green','orange')
        ctx['birth_date'] = slice_list(BirthDate.objects.birth_users(), 3)
        ctx['newbies'] = slice_list(Newbie.objects.all(), 3)
        try:
            ctx['title'] = self.model._meta.verbose_name_plural
        except: pass
        return ctx


class IndexPage(ContextMixin, TemplateView):
    u''' Главная страница '''
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super(IndexPage, self).get_context_data(**kwargs)
        ctx['newssliders'] = NewsSliderItem.objects.filter(is_active=True,
                                                            is_publish=True)
        return ctx
index = IndexPage.as_view()
calendar = IndexPage.as_view(template_name='calendar.html')
company_structure = IndexPage.as_view(template_name='company_structure.html')

class ListPage(ContextMixin, ListView):
    model = News
    paginate_by = 10
    template_name = 'list.html'  
news_list = ListPage.as_view()
ads_list = ListPage.as_view(model=Ad)
books = ListPage.as_view(model=Book)
contests_list = ListPage.as_view(model=Contest)
directions = ListPage.as_view(model=Direction)
quiz_list = ListPage.as_view(model=Quiz)
newbies = ListPage.as_view(model=Newbie)
empltraining_list = ListPage.as_view(model=EmplTraining)
plans = ListPage.as_view(model=Plan,
                        template_name='plans.html')
questions = ListPage.as_view(model=Question, template_name='questions.html')

class CompanyLifePage(IndexPage):
    u''' Жизнь компании '''
    template_name = 'company_life.html'

    def get_context_data(self, **kwargs):
        ctx = super(CompanyLifePage, self).get_context_data(**kwargs)
        ctx['quiz_list'] = slice_list(Quiz.objects.all())
        ctx['image_galleries'] = slice_list(Gallery.objects.filter(glr_type=0))
        ctx['video_galleries'] = slice_list(Gallery.objects.filter(glr_type=1))
        ctx['questions'] = slice_list(Question.objects.all())
        return ctx
company_life = CompanyLifePage.as_view()


class InfoPage(IndexPage):
    u''' Справочная информация '''
    template_name = 'info.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        subsidairies = Subsidairy.objects.filter(phonebook__isnull=False
                                        ).values_list('id', flat=True)
        ctx['phones'] = slice_list(
                            Subsidairy.objects.filter(id__in=subsidairies),
                            5
        )
        ctx['docs'] = slice_list(DocTemplate.objects.all(), 4)
        ctx['galleries'] = slice_list(Gallery.objects.all())
        ctx['plans']=slice_list(Plan.objects.all(), 15)
        return ctx
info = InfoPage.as_view()


class StaffPage(IndexPage):
    u''' Сотрудники '''
    template_name = 'staff.html'

    def get_context_data(self, **kwargs):
        ctx = super(StaffPage, self).get_context_data(**kwargs)
        ctx['company_structure'] = slice_list(
            CompanyStructure.objects.filter(parent__isnull=True),
            5
        )
        st = SystemTunes.objects.all().last()
        if st:
            ctx['system_tunes'] = st
        ctx['new_users'] = slice_list(User.objects.new_users())
        #ctx['on_vacations'] = slice_list(Vacation.objects.on_vacation_users())
        ctx['birth_date'] = slice_list(BirthDate.objects.birth_users())
        ctx['empltraining'] = slice_list(EmplTraining.objects.all())
        return ctx
staff = StaffPage.as_view()


class DetailPage(ContextMixin, DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'

    def get_context_data(self, **kwargs):
        ctx = super(DetailPage, self).get_context_data(**kwargs)
        ctx['reverse_url_name'] = ctx.get('detail_page'
                                    ).__class__._meta.verbose_name_plural.lower()
        return ctx

ads = DetailPage.as_view(model=Ad)
book = DetailPage.as_view(model=Book)
calendar_event = DetailPage.as_view(model=Calendar)
contests = DetailPage.as_view(model=Contest)
direction = DetailPage.as_view(model=Direction)
news = DetailPage.as_view(model=News)
newbie = DetailPage.as_view(model=Newbie)
empltraining = DetailPage.as_view(model=EmplTraining)
question = DetailPage.as_view(model=Question)

class QuizDetail(DetailPage):
    model=Quiz
    template_name='quiz.html'

    def get_context_data(self, **kwargs):
        ctx = super(QuizDetail, self).get_context_data(**kwargs)
        ctx['can_vote'] = self.can_vote()
        ctx['results'] = self.quiz_results()
        return ctx

    def can_vote(self):
        self.quv_set = self.get_object().quizuservote_set
        vote_users_pk = self.quv_set.values_list('user', flat=True)
        return self.request.user.pk not in vote_users_pk

    def quiz_results(self):
        if not self.can_vote():
            quv_set = self.get_object().quizuservote_set.order_by('choice')
            count = quv_set.aggregate(Count('user'))
            by_ch =  quv_set.values('choice__title'
                            ).annotate(num_users=Count('user'))
            return count, by_ch

    def post(self, request, *args, **kwargs):
        if self.can_vote() and self.request.user.is_authenticated():
            postdata = self.request.POST
            QuizUserVote.objects.create(quiz=self.get_object(),
                                        user = self.request.user,
                                        choice_id = postdata.get('quiz_choice'))
            return redirect(self.get_object().get_absolute_url())
        return self.http_method_not_allowed(request)  
quiz = QuizDetail.as_view()

class BirthDetail(DetailPage):
    model=BirthDate
    template_name = 'birth_detail.html'
    def get_context_data(self, **kwargs):
        ctx = super(BirthDetail, self).get_context_data(**kwargs)
        ctx['wish_form'] = WishForm()
        return ctx

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            postdata = self.request.POST
            form = WishForm(postdata)
            if form.is_valid():
                wish = form.save(commit=False)
                wish.user = request.user
                wish.save()
                self.get_object().wishes.add(wish)
        return redirect(self.get_object().get_absolute_url())
birth = BirthDetail.as_view()


class QuestionDetail(DetailPage):
    model=Question
    template_name = 'question_detail.html'
    def get_context_data(self, **kwargs):
        ctx = super(QuestionDetail, self).get_context_data(**kwargs)
        ctx['comment_form'] = CommentForm()
        return ctx

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            postdata = self.request.POST
            form = CommentForm(postdata)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.save()
                self.get_object().comments.add(comment)
        return redirect(self.get_object().get_absolute_url())
question = QuestionDetail.as_view()


class AdCreate(CreateView):
    model = Ad
    fields=('title', 'content')
    template_name = 'create_form.html'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
                ad = form.save(commit=False)
                ad.user = self.request.user
                ad.save()
                return super(AdCreate, self).form_valid(form)
        return self.form_invalid(self, form)
create_ad = AdCreate.as_view()


class QuestionCreate(CreateView):
    model = Question
    fields=('title', 'content')
    template_name = 'create_qform.html'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
                question = form.save(commit=False)
                question.user = self.request.user
                question.save()
                return super(QuestionCreate, self).form_valid(form)
        return self.form_invalid(self, form)
create_question = QuestionCreate.as_view()

main/templates/base.html
{% load conversejs %}

<!DOCTYPE html>
<html>
{% block head %}
    {% include 'partial/head.html' %}
{% endblock %}

{% block body %}
    <body class="w1280px">
        {% block header %}
            {% include 'partial/header.html' %}
        {% endblock %}

        <section>
            <div class="container">
                {% block top %}
                    {% include 'partial/simple_topblock.html' %}
                {% endblock %}
                {% block middle %}
                    {% include 'partial/middleblock.html' %}
                {% endblock %}
            </div>
        </section>


        {% block footer %}
            {% include 'partial/footer.html' %}
        {% endblock %}

        {% if request.user.is_authenticated %}
            {% conversejs_initialize %}
            {% conversejs_chatpanel %}
            {% if user_jid %}
            <script>
                require(['converse'], function (converse) {
                    converse.initialize({
                        allow_otr: true,
                        auto_list_rooms: false,
                        auto_subscribe: false,
                        bosh_service_url: 'https://bind.conversejs.org', // Please use this connection manager only for testing purposes
                        debug: true ,
                        hide_muc_server: false,
                        i18n: locales.ru, // Refer to ./locale/locales.js to see which locales are supported
                        prebind: false,
                        show_controlbox_by_default: true,
                        xhr_user_search: false,
                    });
                    $(document).ready(function () {
                        var form = $("form[id=converse-login]");
                        form.find("input[name=jid]").val('{{user_jid.jid}}');
                        form.find("input[name=password]").val('{{user_jid.password}}');
                        form.submit();
                    });
                });
            </script>
            {% endif %}
        {% endif %}
        {% block extrascripts %}{% endblock %}
    </body>
{% endblock %}
</html>

main/templates/basecontent.html
{% extends 'base.html' %}

{% block top %}
    {% include 'partial/simple_topblock.html' %}
{% endblock %}

{% block middle %}
    {% include 'partial/middleblock.html' with detail_page=0 %}
{% endblock %}

main/templates/calendar.html
{% extends 'basecontent.html' %}
{% block middle %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    {% endblock %}
    <div class="mainblock">
        <h2>Календарь событий</h2>
        {% for event in calendar_events %}
        <div class="textblock eventblock {{clrs|random}}">
            <div class="eventleftblock">
                <div class="eventheader">
                    <time>{{event.start_date}} – {{event.end_date}}</time>
                </div>
                <div class="eventanounce">
                    <h3>{{event.title}}</h3>
                    {{event.content|safe}}
                </div>
            </div>
        </div>
        {% empty %}
            События отсутствуют
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/company_life.html
{% extends 'base.html' %}

{% block middle %}
<div class="middlecontentblock">
    <div class="mediablock contest">
        {% include 'partial/newsbar.html' with newsbar_title='Опросы' list=quiz_list icon='contesticon' link='main:quiz_list' %}
    </div>
    <div class="mediablock bulletinboard">
        <h3>Объявления сотрудников</h3>
        <ul class="newsbarlist">
            {% for page in ads %}
                <li class="{% if item_class%}{{item_class}}{%else%}newsbaritem{%endif%}">
                    <p><time>{{page.created}}</time></p>
                    <p><a href="{{page.get_absolute_url}}" >{{page.title}}</a></p>
                </li>
            {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'main:ads_list'  %}" class="bulletinicon">Читать все объявления сотрудников</a>
            <a href="{% url 'main:create_ad' %}">Добавить объявление</a>
        </div>
    </div>
    <div class="mediablock photoarchive">
        <h3>Карусель фотографий</h3>
        <ul class="mediaarchivelist">
            {% for page in image_galleries %}
                <li class="mediaarchiveitem">
                    <h4><a href="{{page.get_absolute_url}}" class="pseudolink">{{page.title}}</a></h4>
                </li>
            {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'filestorage:image_gallery_list' %}" class="photoicon">Смотреть все фотографии</a>
        </div>
    </div>
    <div class="mediablock videoarchive">
        <h3>Вопросы</h3>
        <ul class="mediaarchivelist">
            {% for page in questions %}
                <li class="mediaarchiveitem">
                    <h4><a href="{{page.get_absolute_url}}" class="pseudolink">{{page.title}}</a></h4>
                </li>
            {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'main:questions' %}" class="videoicon">Смотреть все вопросы</a>
            <a href="{% url 'main:create_question' %}">Добавить вопрос</a>
        </div>
    </div>
    <div class="clear"></div>
</div>
{% endblock %}

main/templates/create_form.html
{% extends 'basecontent.html' %}
{% load widget_tweaks %}
{% block middle %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    {% endblock %}
    <div class="mainblock">
        <div class="textblock newstext">
        {% if request.user.is_authenticated %}
        <form id="ad_form" action="" method="post">
            {% csrf_token %}
            <div class="textblock">
                <p id="form_error" class="error">Введите заголовок</p>
                {% render_field form.title placeholder="Заголовок" %}<br/>
                {{form.content}}
                <button type="submit">Добавить объявление</button>
            </div>
        </form>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/info.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block middle %}
<div class="middlecontentblock">
    <div class="mediablock scheme">
        <h3>Планы и схемы</h3>
        <ul class="schemelist col3">
        {% with plans.count|div:3 as num %}
        {% for plan in plans %}
            <li><a href="{{plan.planfile.url}}" class="fancybox">{{plan.title}}</a></li>
            {% if forloop.counter|divisibleby:num and not forloop.last %}
        </ul>
        <ul class="schemelist col3">            
            {% endif %}
        {% endfor %}
        {% endwith %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'main:plans' %}" class="schemeicon">Смотреть вcе планы и схемы</a>
        </div>
    </div>
    <div class="mediablock doctemplates">
        <h3>Шаблоны документов</h3>
        <ul class="documentslist">
        {% for file in docs %}
            <li class="documentitem {{file.file_type}}">
                <a href="{{file.template.url}}" >{{file.title}}<br/>({{file.get_file_type_display}}, {{file.template.size|filesizeformat}})</a>
            </li>
        {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'infos:files' %}" class="docicon">Смотреть все шаблоны документов</a>
        </div>
    </div>
    <div class="mediablock phonebook">
        <h3>Телефонный справочник дочерних компаний</h3>
        <ul class="phonebooklist">
        {% for subsidairy in phones %}
            <li>
                <span class="phonename"><a href="{{subsidairy.get_absolute_url}}">{{subsidairy.title}}</a></span>
            </li>
        {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'infos:phones' %}" class="phoneicon">Смотреть весь телефонный справочник</a>
        </div>
    </div>
    <div class="mediablock mediaarchive">
        <h3>Медиаархив</h3>
        <ul class="mediaarchivelist">
            {% for page in galleries %}
                <li class="mediaarchiveitem">
                    <h4><a href="{{page.get_absolute_url}}" class="pseudolink">{{page.title}}</a></h4>
                </li>
            {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'filestorage:gallery_list' %}" class="mediaicon">Смотреть весь медиаархив</a>
        </div>
    </div>
    <div class="clear"></div>
</div>
{% endblock %}

main/templates/object_detail.html
{% extends 'basecontent.html' %}

{% block middle %}
    {% include 'partial/middleblock.html' %}
{% endblock %}

main/templates/staff.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block middle %}
<div class="middlecontentblock">
    <div class="mediablock newstaff">
        <h3>Новые сотрудники</h3>
        <ul class="newstafflist">
        {% for user in new_users %}
            <li class="newstaffitem">
                <p><time>{{user.date_joined}}</time></p>
                <p><a href="{{user.get_absolute_url}}">{{user.get_full_name}}</a></p>
            </li>
        {% empty %}
            <li class="newstaffitem">-</li>
        {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'accounts:new_users' %}" class="stafficon">Смотреть всех новых сотрудников</a>
        </div>
    </div>

    <div class="mediablock bulletinboard">
        {% include 'partial/newsbar.html' with newsbar_title='Обучение сотрудников' list=empltraining icon='bulletinicon' link='main:empltraining_list' %}
    </div> 

    <div class="mediablock orgstrukture">
        <h3>Организационная структура</h3>
        {% if system_tunes.cs_image_url %}
            <a class="fancybox" href="{{system_tunes.cs_image.url}}"><img src="{{system_tunes.cs_image_url}}"></a>
        {% else %}
        {% for node in company_structure %}
            <ul class="nomarker nomargin">
                <li>{{ node.name }}
                    {% comment %}
                    {% for child in node.get_children %}
                        <ul class="nomarker">
                            <li>{{ child.name }}</li>
                        </ul>
                    {% endfor %}
                    {% endcomment %}
                </li>
            </ul>
        {% endfor %}
        {%endif%}
        <div class="bottomblock">
            <a href="{% url 'main:company_structure' %}" class="orgstruktureicon">Все подразделения</a>
            <a href="{% url 'main:directions' %}" class="orgstruktureicon">Дирекции</a>
        </div>
    </div>

    
    <div class="mediablock vacationgraph">
        <h3>Дни рождения</h3>
        <ul class="vacationlist">
        {% for bd in birth_date %}
            <li class="vacationitem">
                <p><time>{{bd.birth}}</time></p>
                <p><a href="{{bd.get_absolute_url}}">{{bd.title}}</a></p>
            </li>
        {% empty %}
            <li> --- </li>
        {% endfor %}
        </ul>
        <div class="bottomblock">
            <a href="{% url 'accounts:birthday_users' %}" class="vacationicon">Смотреть все дни рождения</a>
        </div>
    </div>
    <div class="clear"></div>     
</div>
{% endblock %}