accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('accounts.views',
    url(r'^new_users/$', 'new_users', name='new_users'),
    url(r'^on_vacation_users/$', 'on_vacation_users', name='on_vacation_users'),
    url(r'^birthday_users/$', 'birthday_users', name='birthday_users'),
    url(r'^profile/(?P<pk>\d+)/$', 'profile', name='profile'),


    url(r'^userdetails/(?P<pk>\d+)/$', 'userdetails', name='userdetails'),
)

finter/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'main.views.index', name='index'),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'infos/', include('infos.urls', namespace='infos')),
    url(r'', include('main.urls', namespace='main')),
    url(r'filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', 'django.contrib.auth.login', name='login')
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),

    url(r'^ads/$', 'ads_list', name='ads_list'),
    url(r'^create_ad/$', 'create_ad', name='create_ad'),
    url(r'^ads/(?P<pk>\d+)/$', 'ads', name='ads'),
    url(r'^birth/(?P<pk>\d+)/$', 'birth', name='birth'),
    url(r'^books/$', 'books', name='books'),
    url(r'^book/(?P<pk>\d+)/$', 'book', name='book'),
    url(r'^calendar/$', 'calendar', name='calendar'),
    url(r'^calendar/(?P<pk>\d+)/$', 'calendar_event', name='calendar_event'),
    url(r'^company_structure/$', 'company_structure', name='company_structure'),
    url(r'^company_life/$', 'company_life', name='company_life'),
    url(r'^contests/$', 'contests_list', name='contests_list'),
    url(r'^contests/(?P<pk>\d+)/$', 'contests', name='contests'),
    url(r'^directions/$', 'directions', name='directions'),
    url(r'^direction/(?P<pk>\d+)/$', 'direction', name='direction'),
    url(r'^empltraining/$', 'empltraining_list', name='empltraining_list'),
    url(r'^empltraining/(?P<pk>\d+)/$', 'empltraining', name='empltraining'),
    url(r'^questions/$', 'questions', name='questions'),
    url(r'^question/(?P<pk>\d+)/$', 'question', name='question'),
    url(r'^create_question/$', 'create_question', name='create_question'),
    url(r'^quiz/$', 'quiz_list', name='quiz_list'),
    url(r'^quiz/(?P<pk>\d+)/$', 'quiz', name='quiz'),
    url(r'^info/$', 'info', name='info'),
    url(r'^newbies/$', 'newbies', name='newbies'),
    url(r'^newbie/(?P<pk>\d+)/$', 'newbie', name='newbie'),
    url(r'^news/$', 'news_list', name='news_list'),
    url(r'^news/(?P<pk>\d+)/$', 'news', name='news'),
    url(r'^staff/$', 'staff', name='staff'),
    url(r'^plans/$', 'plans', name='plans'),
)

main/forms.py
#coding: utf-8
from django import forms

from ckeditor.widgets import CKEditorWidget

from .models import Ad, Wish, Comment


class WishForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Wish
        fields = 'content',


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Comment
        fields = 'content',


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = 'title', 'content'

main/views.py
#coding: utf-8
from django.contrib.auth import get_user_model
User = get_user_model()
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic.list import ListView

from conversejs.models import XMPPAccount

from filestorage.models import Gallery
from infos.models import DocTemplate, Subsidairy

from .forms import WishForm, CommentForm#, AdForm
from .models import Ad, Book, Calendar, Contest, CompanyStructure
from .models import Direction, BirthDate, Question#, Vacation, 
from .models import News, NewsSliderItem, Quiz, QuizUserVote
from .models import Plan, SystemTunes, Newbie, EmplTraining
from .utils import slice_list

class ContextMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(ContextMixin, self).get_context_data(**kwargs)
        try:
            xmpp_account = XMPPAccount.objects.get(user=self.request.user.pk)
            ctx['user_jid'] = xmpp_account
        except XMPPAccount.DoesNotExist: pass
        ctx['ads'] = slice_list(Ad.objects.all())
        ctx['news'] = slice_list(News.objects.all())
        ctx['calendar_events'] = slice_list(Calendar.objects.all(), 5)
        ctx['clrs'] = ('blue','green','orange')
        ctx['birth_date'] = slice_list(BirthDate.objects.birth_users(), 3)
        ctx['newbies'] = slice_list(Newbie.objects.all(), 3)
        try:
            ctx['title'] = self.model._meta.verbose_name_plural
        except: pass
        return ctx


class IndexPage(ContextMixin, TemplateView):
    u''' Главная страница '''
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super(IndexPage, self).get_context_data(**kwargs)
        ctx['newssliders'] = NewsSliderItem.objects.filter(is_active=True,
                                                            is_publish=True)
        return ctx
index = IndexPage.as_view()
calendar = IndexPage.as_view(template_name='calendar.html')
company_structure = IndexPage.as_view(template_name='company_structure.html')

class ListPage(ContextMixin, ListView):
    model = News
    paginate_by = 10
    template_name = 'list.html'  
news_list = ListPage.as_view()
ads_list = ListPage.as_view(model=Ad)
books = ListPage.as_view(model=Book)
contests_list = ListPage.as_view(model=Contest)
directions = ListPage.as_view(model=Direction)
quiz_list = ListPage.as_view(model=Quiz)
newbies = ListPage.as_view(model=Newbie)
empltraining_list = ListPage.as_view(model=EmplTraining)
plans = ListPage.as_view(model=Plan,
                        template_name='plans.html')
questions = ListPage.as_view(model=Question, template_name='questions.html')

class CompanyLifePage(IndexPage):
    u''' Жизнь компании '''
    template_name = 'company_life.html'

    def get_context_data(self, **kwargs):
        ctx = super(CompanyLifePage, self).get_context_data(**kwargs)
        ctx['quiz_list'] = slice_list(Quiz.objects.all())
        ctx['image_galleries'] = slice_list(Gallery.objects.filter(glr_type=0))
        ctx['video_galleries'] = slice_list(Gallery.objects.filter(glr_type=1))
        ctx['questions'] = slice_list(Question.objects.all())
        return ctx
company_life = CompanyLifePage.as_view()


class InfoPage(IndexPage):
    u''' Справочная информация '''
    template_name = 'info.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        subsidairies = Subsidairy.objects.filter(phonebook__isnull=False
                                        ).values_list('id', flat=True)
        ctx['phones'] = slice_list(
                            Subsidairy.objects.filter(id__in=subsidairies),
                            5
        )
        ctx['docs'] = slice_list(DocTemplate.objects.all(), 4)
        ctx['galleries'] = slice_list(Gallery.objects.all())
        ctx['plans']=slice_list(Plan.objects.all(), 15)
        return ctx
info = InfoPage.as_view()


class StaffPage(IndexPage):
    u''' Сотрудники '''
    template_name = 'staff.html'

    def get_context_data(self, **kwargs):
        ctx = super(StaffPage, self).get_context_data(**kwargs)
        ctx['company_structure'] = slice_list(
            CompanyStructure.objects.filter(parent__isnull=True),
            5
        )
        st = SystemTunes.objects.all().last()
        if st:
            ctx['system_tunes'] = st
        ctx['new_users'] = slice_list(User.objects.new_users())
        #ctx['on_vacations'] = slice_list(Vacation.objects.on_vacation_users())
        ctx['birth_date'] = slice_list(BirthDate.objects.birth_users())
        ctx['empltraining'] = slice_list(EmplTraining.objects.all())
        return ctx
staff = StaffPage.as_view()


class DetailPage(ContextMixin, DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'

    def get_context_data(self, **kwargs):
        ctx = super(DetailPage, self).get_context_data(**kwargs)
        ctx['reverse_url_name'] = ctx.get('detail_page'
                                    ).__class__._meta.verbose_name_plural.lower()
        return ctx

ads = DetailPage.as_view(model=Ad)
book = DetailPage.as_view(model=Book)
calendar_event = DetailPage.as_view(model=Calendar)
contests = DetailPage.as_view(model=Contest)
direction = DetailPage.as_view(model=Direction)
news = DetailPage.as_view(model=News)
newbie = DetailPage.as_view(model=Newbie)
empltraining = DetailPage.as_view(model=EmplTraining)
question = DetailPage.as_view(model=Question)

class QuizDetail(DetailPage):
    model=Quiz
    template_name='quiz.html'

    def get_context_data(self, **kwargs):
        ctx = super(QuizDetail, self).get_context_data(**kwargs)
        ctx['can_vote'] = self.can_vote()
        ctx['results'] = self.quiz_results()
        return ctx

    def can_vote(self):
        self.quv_set = self.get_object().quizuservote_set
        vote_users_pk = self.quv_set.values_list('user', flat=True)
        return self.request.user.pk not in vote_users_pk

    def quiz_results(self):
        if not self.can_vote():
            quv_set = self.get_object().quizuservote_set.order_by('choice')
            count = quv_set.aggregate(Count('user'))
            by_ch =  quv_set.values('choice__title'
                            ).annotate(num_users=Count('user'))
            return count, by_ch

    def post(self, request, *args, **kwargs):
        if self.can_vote() and self.request.user.is_authenticated():
            postdata = self.request.POST
            QuizUserVote.objects.create(quiz=self.get_object(),
                                        user = self.request.user,
                                        choice_id = postdata.get('quiz_choice'))
            return redirect(self.get_object().get_absolute_url())
        return self.http_method_not_allowed(request)  
quiz = QuizDetail.as_view()

class BirthDetail(DetailPage):
    model=BirthDate
    template_name = 'birth_detail.html'
    def get_context_data(self, **kwargs):
        ctx = super(BirthDetail, self).get_context_data(**kwargs)
        ctx['wish_form'] = WishForm()
        return ctx

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            postdata = self.request.POST
            form = WishForm(postdata)
            if form.is_valid():
                wish = form.save(commit=False)
                wish.user = request.user
                wish.save()
                self.get_object().wishes.add(wish)
        return redirect(self.get_object().get_absolute_url())
birth = BirthDetail.as_view()


class QuestionDetail(DetailPage):
    model=Question
    template_name = 'question_detail.html'
    def get_context_data(self, **kwargs):
        ctx = super(QuestionDetail, self).get_context_data(**kwargs)
        ctx['comment_form'] = CommentForm()
        return ctx

    def post(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            postdata = self.request.POST
            form = CommentForm(postdata)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.save()
                self.get_object().comments.add(comment)
        return redirect(self.get_object().get_absolute_url())
question = QuestionDetail.as_view()


class AdCreate(CreateView):
    model = Ad
    fields=('title', 'content')
    template_name = 'create_form.html'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
                ad = form.save(commit=False)
                ad.user = self.request.user
                ad.save()
                return super(AdCreate, self).form_valid(form)
        return self.form_invalid(self, form)
create_ad = AdCreate.as_view()


class QuestionCreate(CreateView):
    model = Question
    fields=('title', 'content')
    template_name = 'create_qform.html'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
                question = form.save(commit=False)
                question.user = self.request.user
                question.save()
                return super(QuestionCreate, self).form_valid(form)
        return self.form_invalid(self, form)
create_question = QuestionCreate.as_view()

main/templates/partial/announcements.html
<div class="announcements">
    <h3>Дни рождения</h3>
    {% if birth_date %}
        <ul class="announcementslist">
            {% for event in birth_date %}
            <a href="{{event.get_absolute_url}}">
            <li class="announcement"><time>{{event.birth_date}}</time> {{event.title}}</li>
            </a>
            {% endfor%}
            {% comment %}
            {% for event in calendar_events %}
            <a href="{{event.get_absolute_url}}">
            <li class="announcement"><time>{{event.start_date}} – {{event.end_date}}</time> {{event.title}}</li>
            </a>
            {% endfor%}
            {% endcomment %}
        </ul>
    {% endif %}
    <a href="{% url 'accounts:birthday_users' %}" class="allannouncements eventscalendaricon">Смотреть все<br/>дни рождения</a>
    {% if newbies %}
</div>
<div class="announcements">
    <h3>Новички</h3>
        <ul class="announcementslist">
            {% for event in newbies %}
            <a href="{{event.get_absolute_url}}">
            <li class="announcement">{{event.title}}</li>
            </a>
            {% endfor%}
        </ul>
    <a href="{% url 'main:newbies' %}" class="allannouncements eventscalendaricon">Смотреть<br/>все новички</a>
    {% endif %}
</div>

main/templates/partial/footer.html
<footer>
    <div class="container">
        <div class="copyright">
            Экспофорум &copy; 2014
        </div>
        <div class="footercontacts">
            +7 (812) 240-40-40  <a href="mailto:info@expoforum.ru">info@expoforum.ru</a>
        </div>
        <div class="footersocial">
            <p>Экспофорум в соцсетях:</p>
            <ul class="sociallinks">
                <li><a href="#" class="socialicon vkcom">vkcom</a></li>
                <li><a href="#" class="socialicon facebook">facebook</a></li>
                <li><a href="#" class="socialicon googleplus">googleplus</a></li>
                <li><a href="#" class="socialicon twitter">twitter</a></li>
                <li><a href="#" class="socialicon youtube">youtube</a></li>
            </ul>
        </div>
    </div>
{% block footer_extra_scripts%}
<script>ang('a.fancybox').fancybox();</script>
{% endblock %}
</footer>

main/templates/partial/head.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

{% load conversejs %}
<head>
    <title>F-International</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <link href="{{STATIC_PREFIX}}css/jquery.jgrowl.min.css" rel="stylesheet" type="text/css" />
    <link href="{{STATIC_PREFIX}}css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="{{STATIC_PREFIX}}css/owl.theme.css" rel="stylesheet" type="text/css" />
    <link href="{{STATIC_PREFIX}}css/themes/default/style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{STATIC_PREFIX}}css/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
    <link href="{{STATIC_PREFIX}}css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-ui-1.10.4.min.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.jgrowl.min.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}js/main.js"></script>
    <script type="text/javascript" src="{{STATIC_PREFIX}}ckeditor/ckeditor/ckeditor.js"></script>
    <!--[if lt IE 9]>
        <script src="{{STATIC_PREFIX}}js/html5shiv.js"></script>
    <![endif]-->
    <script type="text/javascript">
        var ang = jQuery.noConflict();
        ang(document).ready(function () {
                var slideNav = ang('#slidernavlist');
                var slideList = ang('#promoslider > ul');
                
                ang('.slidernavlink').click(function(e){
                    e.preventDefault();
                    var slideNum = $(this).parent().index();
                    changeslide(slideNum,slideNav,slideList);
                    });
                ang('#promoslider').owlCarousel({
                    navigation : true, // Show next and prev buttons
                    slideSpeed : 300,
                    paginationSpeed : 400,
                    pagination:true,
                    singleItem:true,
                    stopOnHover:true,
                    navigationText:["<a class='bannersnav prev'>&lt;</a>","<a class='bannersnav next'>&gt;</a>"]
                    });
                slideNav.find('li:first').find('a').trigger('click');
                var timerId = setInterval(nextSlide, 10000,slideNav);
        });
    </script>
    <script type="text/javascript">
        ang(function() {
          if (typeof CKEDITOR !== 'undefined') {
            CKEDITOR.config.disableNativeSpellChecker = false;
            //CKEDITOR.config.contentsCss = '/static/css/style.css'
            CKEDITOR.config.forcePasteAsPlainText = true;

            CKEDITOR.on('dialogDefinition', function (ev) {
                var dialogName = ev.data.name;
                var dialogDefinition = ev.data.definition;
                dialogDefinition.minHeight =100;
                dialogDefinition.minWidth = 400;
                var editor = ev.editor;

                dialogDefinition.removeContents('Link');
                dialogDefinition.removeContents('advanced');

                if (dialogName == 'image') {
                    var infoTab = dialogDefinition.getContents('info');
                    dialogDefinition.onOk = function (e) {
                        console.log(dialogDefinition.dialog.getValueOf("info", "txtHeight"));
                        var imageSrcUrl = e.sender.originalElement.$.src;
                        var width = e.sender.originalElement.$.width;
                        var height = e.sender.originalElement.$.height;
                        var txtHeight = dialogDefinition.dialog.getValueOf("info", "txtHeight");
                        var txtWidth = dialogDefinition.dialog.getValueOf("info", "txtWidth");
                        if (txtHeight) {
                          height = txtHeight;
                        };
                        if (txtWidth) {
                          width = txtWidth;
                        };
                        imageSrcUrl = imageSrcUrl.replace(/^.*\/\/[^\/]+/, '');
                        var imgHtml = CKEDITOR.dom.element.createFromHtml('<a class=\"fancybox\" href=\"' + imageSrcUrl + '\"><img src=' + imageSrcUrl + ' width=\"' + width + '\" height=\"' + height + '\" alt=\"\" /></a>');
                        editor.insertElement(imgHtml);
                    };

                    infoTab.remove('txtHSpace');
                    infoTab.remove('txtVSpace');
                    infoTab.remove('txtBorder');
                    //infoTab.remove('txtHeight');
                    //infoTab.remove('txtWidth');
                    infoTab.remove('cmbAlign');
                    infoTab.remove('ratioLock');

                    infoTab.get('htmlPreview').style = 'display: none;'
                }
            });
          }
        });
    </script>
    {% conversejs_static %}
</head>

main/templates/partial/header.html
{% load static %}
{% load thumbnail %}
{% get_static_prefix as STATIC_PREFIX %}
<header>
    <div class="container">
        <div class="headlogo">
            <a href="/">ExpoLife</a>
        </div>
        <div class="headcontacts">
            +7 (812) <b>240-40-40</b> <a href="mailto:info@expoforum.ru">info@expoforum.ru</a>
        </div>
        <div class="rightsection">
        {% if user.is_authenticated %}
            <div class="headerprofile">
                <div class="miniprofileblock">
                    <div class="miniavatar">
                        {% if user.avatar %}
                        {% thumbnail user.avatar 50x50 upscale as thumb %}
                        <img src="{{thumb.url}}" alt="{{user.get_full_name_without_post}}">
                        {% endif %}
                    </div>
                    <div class="miniuserinfo">
                        <p class="miniusername"><a href="{{user.get_absolute_url}}">{{user.get_full_name_without_post}}</a></p>
                        <p class="miniuserdescr">{{user.post}}</p>
                    </div>
                </div>
                <form class="logout" action="{% url 'rest_framework:logout' %}?next=/" method="post">
                    {% csrf_token %}
                    <button type="submit" class="greenbtn">Выйти</button>
                </form>
            </div>
        {% else %}
            <div class="headerlogin">
                <form class="" action="{% url 'rest_framework:login' %}" method="post">
                    {% csrf_token %}
                    <input type="e-mail" name="username" value="" placeholder="Логин" maxlength="100" required="required">
                    <input type="password" name="password" value="" placeholder="Пароль" maxlength="100" required="required">
                    <button type="submit" class="lightbluebtn">Войти</button>
                </form>
            </div>
        {% endif %}
        </div>
    </div>
</header>

main/templates/partial/left_middle.html
<div class="newsbar">
    <h3>Интерактивный план комплекса</h3>
    <p>Находится в разработке</p>
</div>
<div class="clear"></div>
<div class="newsbar">
    <h3>Телефонный справочник</h3>
    <p>Находится в разработке</p>
</div>
<div class="clear"></div>
<div class="newsbar">
    <h3>Подача заявок</h3>
    <p>Находится в разработке</p>
</div>

main/templates/partial/middleblock.html
{% if type %}
<div class="middlecontentblock">
    <div class="mediablock newsbar">
        {% include 'partial/newsbar.html' with newsbar_title='Новости' list=news link='main:news_list' icon='allnewslink newsicon' %}
    </div>
    <div class="mediablock bulletinboard">
        {% include 'partial/newsbar.html' with newsbar_title='Объявления' list=ads icon='bulletinicon' link='main:ads_list' %}
    </div>
    <div class="clear"></div>
</div>
{% else %}
<div class="middlecontentblock">
    {% block sidebar %}
    <div class="sidebar">
        {% include 'partial/announcements.html' %}
    </div>
    {% endblock %}
    <div class="mainblock">
        <div class="textblock newstext">
        {% block detail_page %}
            <p><a href="{{ detail_page.list_url }}">Все {{reverse_url_name}}</a></p>
            <h2>{{ detail_page.title }}</h2>
            <time>{{ detail_page.created }}</time>
            {% block content %}
                {{detail_page.content|safe}}
            {% endblock %}
        {% endblock %}
        </div>
    </div>
</div>
{% endif %}

main/templates/partial/newsbar.html
<h3>{{newsbar_title}}</h3>
<ul class="newsbarlist">
    {% for page in list %}
        <li class="{% if item_class%}{{item_class}}{%else%}newsbaritem{%endif%}">
            <p><time>{{page.created}}</time></p>
            <p><a href="{{page.get_absolute_url}}" >{{page.title}}</a></p>
        </li>
    {% endfor %}
</ul>
<div class="bottomblock">
    <a href="{% url link %}" class="{{icon}}">Читать все {{newsbar_title|lower}}</a>
</div>

main/templates/partial/paginator.html
{% if is_paginated %}
<div class="paginationblock">
    <ul class="pageslist">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}
        {% for n in paginator.page_range %}
        <li><a href="?page={{n}}" {% ifequal n page_obj.number %}class="currentPage"{%endifequal%}>{{n}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">next</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}

main/templates/partial/partners.html
<div class="partnersblock">
    <h3>Партнеры</h3>
    <div class="partnersview" id="partners">
        <ul class="partnerslist">
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner1.png" alt="pertner1"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner2.png" alt="pertner2"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner3.png" alt="pertner3"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner4.png" alt="pertner4"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner5.png" alt="pertner5"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner6.png" alt="pertner6"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner1.png" alt="pertner1"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner2.png" alt="pertner2"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner3.png" alt="pertner3"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner4.png" alt="pertner4"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner5.png" alt="pertner5"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner6.png" alt="pertner6"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner1.png" alt="pertner1"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner2.png" alt="pertner2"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner3.png" alt="pertner3"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner4.png" alt="pertner4"></a>
            </li>
            <li class="partnerscell">
                <a href="#" class="partnerbox"><img src="/static/images/partner5.png" alt="pertner5"></a>
                <a href="#" class="partnerbox"><img src="/static/images/partner6.png" alt="pertner6"></a>
            </li>
        </ul>
    </div>
    <a href="#" class="partnersnav prev" id="prevslide">&lt;</a>
    <a href="#" class="partnersnav next" id="nextslide">&gt;</a>
</div>

main/templates/partial/simple_topblock.html
<div class="topcontentblock">
    <nav class="mainnav">
        <ul class="mainnavlist">
            <li><a href="{% url 'main:index' %}" class="mainnavlink">Главная</a></li>
            <li><a href="{% url 'main:company_life' %}" class="mainnavlink">Жизнь компании</a></li>
            <li><a href="{% url 'main:staff' %}" class="mainnavlink">Сотрудники</a></li>
            <li><a href="{% url 'main:info' %}" class="mainnavlink">Справочная информация</a></li>
            
        </ul>
    </nav>
</div>